### ISSUE TITLE
stack_sky files

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#10]
Maybe I am misinterpreting but I would have expected the stack_sky files to be purely the model from the Kelson+03 method (i.e. the stack of rectified skymodel files). Instead they look the same as the _stack files in the output folder?

Maybe not a bug?

**Comment by siriobelli** [comment]
Kind of a bug. The way it is implemented now makes sense when the AB dithering is used, so that the stack of A+B contains basically just the sky. But we should implement the "correct" way that you describe.

**Comment by siriobelli** [comment]
Now the stacked sky frames are derived from the sky model, which is the correct way.
