### ISSUE TITLE
Option to output in units of Angstroms

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#11]
It would be nice to be able to output the final wavelength calibrated files in units of Angstroms

**Comment by siriobelli** [comment]
Agreed, and this should be the default for LRIS

**Comment by siriobelli** [comment]
Unfortunately this is not easy to do because the line lists are all in micron and are used throughout the code, also after the final data products are written. I think it would make things too complicated and it would not be worth it.

**Comment by pboley** [comment]
What about just multiplying by 1e4 when writing the WCS information of the final combined files if a "settings.output_angstroms" flag is set? Should be easy.

**Comment by siriobelli** [comment]
The problem is that after the combine step there are still the checkdata and extract modules, and both of them use the wavelength axis for identifying lines and plotting.

**Comment by pboley** [comment]
Could use the CUNIT keyword from the FITS header. Or just the value of settings.output_angstroms from the fuel structure.
