### ISSUE TITLE
Most recent version doesn't perform cosmic ray subtraction

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#12]
For some reason after the exptime/elaptime fix flame_correct does not perform the L.A.Cosmic cosmic ray detection

**Comment by siriobelli** [comment]
Did you make sure to set the fuel.util.clean_individual_frames flag to 1 *after* the initialization?

**Comment by tomjf** [comment]
Not initially. I had this in the driver.

```idl

  ; there are lots of cosmic rays on each individual frame
  input.clean_individual_frames = 1

  ;**********************************
  ;**********************************


  ; initialize and create the fuel structure
  fuel = flame_initialize_lris(input)

```

I tried with this

```idl
  ; there are lots of cosmic rays on each individual frame
  input.clean_individual_frames = 1

  ;**********************************
  ;**********************************


  ; initialize and create the fuel structure
  fuel = flame_initialize_lris(input)
  input.clean_individual_frames = 1

```

and it made no difference.

Why would it matter whether you set this parameter before or after the initialization?

**Comment by tomjf** [comment]
oops I realise the final line should probably be

```idl
fuel.input.clean_individual_frames = 1
```

Still doesn't make a difference though.

**Comment by siriobelli** [comment]
It's in the fuel.util structure, not fuel.input! If you run fuel.input.clean_individual_frames = 1 you should get an error because there is no such field in fuel.input.
