### ISSUE TITLE
Option for standard stars/1 frame?

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#15]
I tried to reduce 1 standard star frame so flame would correct the frame, wavelength calibrate it and do the sky subtraction ready for flux calibration. 

I had to make a duplicate copy of the frame to get flame to run as it wouldn't accept just 1 frame. Not sure if this is a bug or feature?

**Comment by siriobelli** [comment]
Definitely a bug. Funny that I've never tested flame using only one frame!

**Comment by siriobelli** [comment]
This should have been fixed, let me know if it works.
