### ISSUE TITLE
Saving fuel

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#2]
As an aside it might be nice to automatically save the fuel structure after each flame routine has completed successfully with the name of the last completed routine in the filename and overwriting the old one each time. 

[In addition you could maybe write the driver to have a parameter to not read the saved structure or to read it and pick up where flame last was saved (this might be unnecessary/confusing)]

**Comment by siriobelli** [comment]
Great idea! I added the routines flame_util_module_start and flame_util_module_end that save the routine name and time stamp in fuel.util, display some information in the terminal, and save fuel.sav in the intermediate directory.
