### ISSUE TITLE
Manually input slit edges in docs

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#3]
I know it is already in bold, to be added to the docs but if I don't use `input.slit_position_file = 'slit_edges.reg'` on LRIS the code fails as expected. 

I think it would be good to document this but also clarify whether these edges need to be defined on the science frame or flat (if the flat is used). So does the slitflat_offset apply an offset to the manually defined slit edges on the individual OBs so it matches the flat?

**Comment by siriobelli** [comment]
Yes, it's very ambiguous now. The edges in the region file need to be defined on the frame that is actually used for the slit detection (i.e., the flat, if used). The slits are identified and then the offset is applied. The final slits region file that is written includes the offset and should match the science frames. There is now also a slits_raw.reg file that shows the actual measurements of the slit edges, and this does not include the offset.

I'll add this information to the manual.

**Comment by siriobelli** [comment]
This should now be clear in the manual.
