### ISSUE TITLE
LRIS Exptime/Elaptime

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#6]
Error in flame_correct.pro. This looks for keyword 'EXPTIME' in the LRIS header. The correct keyword is 'ELAPTIME' which is 1800s - big error if 1 second is used instead!

Currently:
```idl
    exptime = fxpar(header, 'EXPTIME', missing=-1.0)
    if exptime EQ -1.0 then begin
      print, 'EXPTIME not found; setting to 1 second.'
      exptime = 1.0
    endif
```

Should be something like this as a botch (? probably wrong syntax):

```idl
if fuel.instrument EQ 'lris'
    exptime = fxpar(header, 'ELAPTIME', missing=-1.0)
endif else
    exptime = fxpar(header, 'EXPTIME', missing=-1.0)
endelse
if exptime EQ -1.0 then begin
   print, 'EXPTIME not found; setting to 1 second.'
   exptime = 1.0
endif
```

**Comment by tomjf** [comment]
Or I guess intialize lris could change this keyword in the header.

**Comment by siriobelli** [comment]
It looks like only the blue side has this problem. I think that the universally recognized keyword is EXPTIME so the best solution is to first check if that exists, and if it doesn't then use ELAPTIME.

The golden rule of flame is to keep strictly separated the data reduction part from the instrument-specific part. So this should definitely be dealt with during initialize_lris. I added a part that creates the EXPTIME keyword if it doesn't exist, and copies the content from ELAPTIME.

Please test it (note that the driver changed) and if it works you can close this.

**Comment by tomjf** [comment]
Thanks! Yep it seems for some reason the red side has exptime in the header but not on the blue side. I'll try the new update.
