### ISSUE TITLE
Flux calibration

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#7]
Does flame perform a flux calibration?

**Comment by siriobelli** [comment]
Nope. For the flux calibration you need first to extract 1D spectra, which is currently not implemented. I may add the 1D extraction in the future, but even so the flux calibration requires a lot of steps (reduce and extract science spectrum, reduce and extract the standard star spectrum, and use an appropriate template for the standard star) and I don't see how it could be reasonably automated.
