### ISSUE TITLE
Getslits blue side error - illegal subscript range: YD

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#8]
Not sure what is different from the red side but I get this error with getslit on the blue side data.

```idl

-------------------------------------
---      flame_getslit        ---
-------------------------------------

Finding the edges of slit 1 - 
% Illegal subscript range: YD.
% Execution halted at: FLAME_GETSLITS_CROSSCORR  385 /Users/tom/idl/flame/pro/flame_getslits.pro
%                      FLAME_GETSLITS_MULTISLIT  530 /Users/tom/idl/flame/pro/flame_getslits.pro
%                      FLAME_GETSLITS    731 /Users/tom/idl/flame/pro/flame_getslits.pro
%                      $MAIN$  

```

**Comment by tomjf** [comment]
Do you know why this is happening? It's still an error in the latest version and I can't figure out why.

**Comment by siriobelli** [comment]
Unfortunately I don't know what's the problem. I think it's an error message from c_correlate(), I guess there is something wrong with image[*,i_row] or ref_shift. When I have time I'll look into it.
